AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LogGroupToSlack

  Template for LogGroupToSlack

Globals:
  Function:
    Timeout: 3

Resources:
  LogGroupToSlackFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: LogGroupToSlack/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        LogGroupToSlack:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: "/ecs/website"
            FilterPattern: ""

Outputs:
  LogGroupToSlackFunction:
    Description: "LogGroupToSlack Lambda Function ARN"
    Value: !GetAtt LogGroupToSlackFunction.Arn
  LogGroupToSlackFunctionIamRole:
    Description: "Implicit IAM Role created for LogGroupToSlack function"
    Value: !GetAtt LogGroupToSlackFunctionRole.Arn
